name: Ubuntu 22.04 VPS

on:
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-22.04
    timeout-minutes: 360

    steps:
      - name: Update
        run: |
          sudo apt update

      - name: Install SSH
        run: |
          sudo apt install -y openssh-server
          sudo systemctl enable ssh
          sudo systemctl start ssh

      - name: Set Password
        run: |
          echo "runner:123456" | sudo chpasswd

      - name: Install XFCE + VNC
        run: |
          sudo apt install -y xfce4 xfce4-goodies tightvncserver

      - name: Keep Alive
        run: |
          while true; do
            echo "Running..."
            sleep 300
          done
